spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: products-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

        - id: orders-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**

        - id: deliveries-service
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/**

        - id: monitoring-service
          uri: http://localhost:9090
          predicates:
            - Path=/monitoring/**
server:
  port: 8080